#!/bin/bash

if ! grep -qv '^#' secrets.cfg; then
  echo "Need to populate secrets.cfg!"
else
  set -o allexport
  source secrets.cfg
  set +o allexport
fi

export SOPEL_CONFIG=$PWD/EV0003.cfg

# run sopel command (with suffix through symlink)
me=`basename "$0"`
sopel="sopel${me#EV0003}"
exec $sopel "$@"
