#!/bin/bash

if ! grep -qv '^#' secrets.cfg; then
  echo "Need to populate secrets.cfg!"
  exit 1
fi

set -o allexport
source secrets.cfg
set +o allexport

export SOPEL_CONFIG=$PWD/EV0003.cfg

sopel "$@"
